version: '3'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    environment:
      - PGHOST=postgres
      - PGUSER=postgres_user
      - PGPASSWORD=root
      - PGDATABASE=jobeng
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=jobeng
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

