import Head from "next/head";
import Image from "next/image";
import Aside from "../components/aside";
import FilterNav from "../components/filterNav";
import Layout from "../components/layout";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="wrapper w-full flex flex-col flex-grow scroll-smooth py-8 px-10 overflow-auto">
          <FilterNav />
          <div className="main-container flex flex-grow pt-8">
          <Aside />
            <div className="searched-jobs flex flex-col flex-grow pl-10">
              <div className="searched-bar flex items-center justify-between animate-slideY ">
                <div className="searched-show text-[19px] font-semibold">
                  <p> Showing 0 Jobs </p>
                </div>
                <div className="searched-sort">
                  Sort by: <span className="post-time">Newest Post </span>
                  <span className="menu-icon">▼</span>
                </div>
              </div>
             {/* job card  */}
            </div>
          </div>
        </div>
      </main>
    </Layout>
  );
}
