import Head from "next/head";
import Image from "next/image";
import Aside from "../components/aside";
import FilterNav from "../components/filterNav";
import Layout from "../components/layout";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="wrapper w-full flex flex-col flex-grow scroll-smooth py-8 px-10 overflow-auto">
          <FilterNav />
          <div className="main-container flex flex-grow pt-8">
          <Aside />
            <div className="searched-jobs">
              <div className="searched-bar">
                <div className="searched-show">
                  <p> Showing 0 Jobs </p>
                </div>
                <div className="searched-sort">
                  Sort by: <span className="post-time">Newest Post </span>
                  <span className="menu-icon">▼</span>
                </div>
              </div>
              {/* <div className="job-cards"> */}
              {/*     <div className="job-card"> */}
              {/*       <div className="job-card-header"> */}
              {/*         <%= card.company.toUpperCase() %> */}
              {/*           <div className="menu-dot"></div> */}
              {/*       </div> */}
              {/*       <div className="job-card-title"> */}
              {/*         <%= card.title %> */}
              {/*       </div> */}
              {/*       <div className="job-card-subtitle"> */}
              {/*         <%= card.description %> */}
              {/*       </div> */}
              {/*       <div className="job-detail-buttons"> */}
              {/*         <button className="search-buttons detail-button"> */}
              {/*           <%= card.location %> */}
              {/*         </button> */}
              {/*         <button className="search-buttons detail-button">Full Time</button> */}
              {/*         <!-- <button className="search-buttons detail-button">Senior Level</button> --> */}
              {/*       </div> */}
              {/*       <div className="job-card-buttons"> */}
              {/*         <button className="search-buttons card-buttons">Apply Now</button> */}
              {/*         <button className="search-buttons card-buttons-msg">Overview</button> */}
              {/*       </div> */}
              {/*     </div> */}
              {/* </div> */}
            </div>
          </div>
        </div>
      </main>
    </Layout>
  );
}
